### ISSUE TITLE
Sphinx module problem

### ISSUE THREAD

**Issue by psarahdactyl** [patrickmineault/codebook#26]
Hi,
I am trying to build this jupyter notebook and I get these errors even after `pip install sphinx` and `python -m pip install sphinxext-opengraph`

The conf file already has these lines:
```
sphinx:
  extra_extensions:
  - sphinxext.opengraph
 ```
so I don't know what the problem is?

```
Extension error:
Could not import extension sphinxext.opengraph (exception: No module named 'sphinxext')
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sphinx/registry.py", line 425, in load_extension
    mod = import_module(extname)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'sphinxext'
```

**Comment by patrickmineault** [comment]
Could you print the output `pip freeze` in the environment where you're running jupyterbook? Could you also run `which python` and `python -V`?

**Comment by psarahdactyl** [comment]
sure!
```
| 💯 => pip freeze
alabaster==0.7.12
anyio==3.6.1
appnope==0.1.2
argon2-cffi==21.3.0
argon2-cffi-bindings==21.2.0
asttokens==2.0.5
attrs==21.4.0
Babel==2.10.3
backcall==0.2.0
beautifulsoup4==4.11.1
bleach==4.1.0
certifi==2022.9.24
cffi==1.15.0
charset-normalizer==2.1.1
click==8.1.3
colorama==0.4.5
cycler==0.10.0
debugpy==1.5.1
decorator==5.1.1
defusedxml==0.7.1
docutils==0.17.1
entrypoints==0.4
executing==0.8.3
fastjsonschema==2.16.2
geomstats==2.4.2
gitdb==4.0.9
GitPython==3.1.27
greenlet==1.1.3
idna==3.4
imagesize==1.4.1
importlib-metadata==5.0.0
ipykernel==6.9.1
ipython==8.1.1
ipython-genutils==0.2.0
ipywidgets==7.6.5
jedi==0.18.1
Jinja2==3.0.3
joblib==1.1.0
jsonschema==3.2.0
jupyter==1.0.0
jupyter-book==0.13.1
jupyter-cache==0.4.3
jupyter-client==7.1.2
jupyter-console==6.4.3
jupyter-core==4.9.2
jupyter-server==1.19.1
jupyter-server-mathjax==0.2.6
jupyter-sphinx==0.3.2
jupyterlab-pygments==0.1.2
jupyterlab-widgets==1.0.2
kiwisolver==1.3.2
latexcodec==2.0.1
linkify-it-py==1.0.3
lxml==4.9.1
markdown-it-py==1.1.0
MarkupSafe==2.1.0
matplotlib==3.4.3
matplotlib-inline==0.1.3
mdit-py-plugins==0.2.8
mistune==0.8.4
myst-nb==0.13.2
myst-parser==0.15.2
nbclient==0.5.12
nbconvert==6.5.4
nbdime==3.1.1
nbformat==5.6.1
nest-asyncio==1.5.4
notebook==6.4.8
numpy==1.21.2
packaging==21.3
pandas==1.4.1
pandocfilters==1.5.0
parso==0.8.3
pexpect==4.8.0
pickleshare==0.7.5
Pillow==8.3.2
prometheus-client==0.13.1
prompt-toolkit==3.0.28
ptyprocess==0.7.0
pure-eval==0.2.2
pybtex==0.24.0
pybtex-docutils==1.0.2
pycparser==2.21
pydata-sphinx-theme==0.8.1
Pygments==2.11.2
pyparsing==2.4.7
pyrsistent==0.18.1
python-dateutil==2.8.2
pytz==2021.3
PyYAML==6.0
pyzmq==22.3.0
qtconsole==5.2.2
QtPy==2.0.1
requests==2.28.1
scikit-learn==1.0.2
scipy==1.7.3
Send2Trash==1.8.0
six==1.16.0
smmap==5.0.0
sniffio==1.3.0
snowballstemmer==2.2.0
soupsieve==2.3.2.post1
Sphinx==4.5.0
sphinx-book-theme==0.3.3
sphinx-comments==0.0.3
sphinx-copybutton==0.5.0
sphinx-external-toc==0.2.4
sphinx-jupyterbook-latex==0.4.7
sphinx-multitoc-numbering==0.1.3
sphinx-thebe==0.1.2
sphinx-togglebutton==0.3.2
sphinx_design==0.1.0
sphinxcontrib-applehelp==1.0.2
sphinxcontrib-bibtex==2.5.0
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp==2.0.0
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml==1.1.5
SQLAlchemy==1.4.41
stack-data==0.2.0
terminado==0.13.3
testpath==0.6.0
threadpoolctl==3.1.0
tinycss2==1.1.1
tornado==6.1
traitlets==5.1.1
uc-micro-py==1.0.1
urllib3==1.26.12
wcwidth==0.2.5
webencodings==0.5.1
websocket-client==1.4.1
widgetsnbextension==3.5.2
zipp==3.8.1
```
I guess it's weird that opengraph isn't shown in the freeze. it's not in pip list either. but when I install it keeps saying `Requirement already satisfied`
```
| 💯 => which python
python is /Users/sak/opt/anaconda3/bin/python
python is /usr/local/bin/python
python is /usr/local/bin/python
python is /usr/local/bin/python
```
python version is `Python 3.9.12`

**Comment by patrickmineault** [comment]
Weird. You can deactivate opengraph by deleting it from the config if you want, it just creates cards for social media, it's not necessary to build the book.

If you are set on making it work, you can try creating a new conda environment, activating and installing:

```
conda create --name cb python=3.9
conda activate cb
pip install -r requirements.txt
jupyter-book build . --all
```

**Comment by psarahdactyl** [comment]
thanks! I didn't know what opengraph was for. After removing that from the config it worked fine :)
I also tried what you suggested above and it worked with opengraph.
Looking at the html in my browser worked well!

However, I couldn't get netlify to work due to permissions it seems. or maybe my github OAuth went wrong somewhere. but that's a separate issue

```
| 💯 => sudo netlify deploy --prod
Please provide a publish directory (e.g. "public" or "dist" or "."):
/Users/sak/Downloads/again/codebook
? Publish directory /Users/sak/Downloads/again/codebook
Deploy path:        /Users/sak/Downloads/again/codebook
Configuration path: /Users/sak/Downloads/again/codebook/netlify.toml
Deploying to main site URL...
 ›   Warning: JSONHTTPError:  401
 ›   Warning:
{
  "name": "JSONHTTPError",
  "status": 401,
  "json": {
    "code": 401,
    "message": "Access Denied"
  }
}

 ›   JSONHTTPError: Unauthorized
```
```
| 💯 => sudo netlify status
──────────────────────┐
 Current Netlify User │
──────────────────────┘
Email: <redacted lol>
Teams:
  psarahdactyl's team: Collaborator
────────────────────┐
 Netlify Site Info  │
────────────────────┘
Current site: fervent-carson-5a9d17
Netlify TOML: /Users/sak/Downloads/again/codebook/netlify.toml
Admin URL:    https://app.netlify.com/sites/fervent-carson-5a9d17
Site URL:     https://goodresearch.dev
Site Id:      f0bcb2b1-3782-4a4b-8611-94f5412b4f76
```

**Comment by patrickmineault** [comment]
If you want to locally test your build of the jupyterbook, then you should use `netlify dev -d _build/html`. deploy won't work because you don't have the permissions to directly edit the website – if you want to change the website, send a PR, and once I accept the changes the website will be redeployed by Github.

**Comment by psarahdactyl** [comment]
oh, yeah I just realized I was following the README from this link https://zenodo.org/record/5796873

**Comment by patrickmineault** [comment]
I'm going to close as stale
